version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=crawlerDB
      - POSTGRES_USER=DBadmin
      - POSTGRES_PASSWORD=PGadminDB
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - 6379:6379
  
  celery:
    build:  .
    container_name:  celery_worker
    command:  celery -A myproject worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
  
  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A myproject beat --loglevel=info
    depends_on:
      - celery
      - redis

volumes:
  postgres_data:
