# Generated by Django 5.1.6 on 2025-02-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_directory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
